-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default",
    user_role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.gate
(
    gate_no "char" NOT NULL,
    opening_time timestamp without time zone,
    closing_time timestamp without time zone,
    created_on timestamp without time zone,
    created_by "char",
    updated_on timestamp without time zone,
    updated_by "char",
    PRIMARY KEY (gate_no)
);

CREATE TABLE IF NOT EXISTS public.parking_spot
(
    parking_spot_id "char" NOT NULL,
    parking_type "char",
    charge_per_hr integer,
    occupied boolean,
    vehicle_no "char",
    created_on timestamp without time zone,
    created_by "char",
    updated_on timestamp without time zone,
    updated_by "char",
    PRIMARY KEY (parking_spot_id)
);

CREATE TABLE IF NOT EXISTS public.ticket
(
    ticket_id integer NOT NULL,
    parking_spot_id "char" NOT NULL,
    vehicle_no "char",
    entry_time timestamp without time zone,
    exit_time timestamp without time zone,
    total_charge double precision NOT NULL,
    manage_by "char",
    entry_gate "char",
    exit_gate "char",
    created_on timestamp without time zone,
    created_by "char",
    updated_on timestamp without time zone,
    updated_by "char",
    PRIMARY KEY (ticket_id)
);

CREATE TABLE IF NOT EXISTS public.manager
(
    manager_id integer NOT NULL,
    manager_name "char" NOT NULL,
    slot "char",
    gate_no "char",
    created_on timestamp without time zone,
    created_by "char",
    updated_on timestamp without time zone,
    updated_by "char",
    PRIMARY KEY (manager_id)
);

CREATE TABLE IF NOT EXISTS public.vehicle
(
    vehicle_no "char" NOT NULL,
    vehicle_type "char" NOT NULL,
    owner_name "char" NOT NULL,
    owner_contact integer NOT NULL,
    vehicle_color "char",
    vehicle_brand "char",
    park_status "char",
    manager_id integer,
    created_on timestamp without time zone,
    created_by "char",
    updated_on timestamp without time zone,
    updated_by "char",
    PRIMARY KEY (vehicle_no)
);

CREATE TABLE IF NOT EXISTS public.parking_position
(
    parking_spot_id "char",
    nearest_gate_no "char",
    cordinate integer[]
);

ALTER TABLE IF EXISTS public.parking_spot
    ADD FOREIGN KEY (vehicle_no)
    REFERENCES public.vehicle (vehicle_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket
    ADD FOREIGN KEY (vehicle_no)
    REFERENCES public.vehicle (vehicle_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket
    ADD FOREIGN KEY (entry_gate)
    REFERENCES public.gate (gate_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket
    ADD FOREIGN KEY (exit_gate)
    REFERENCES public.gate (gate_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.manager
    ADD FOREIGN KEY (gate_no)
    REFERENCES public.gate (gate_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehicle
    ADD FOREIGN KEY (manager_id)
    REFERENCES public.manager (manager_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;